var likecount=9;
var likespan1 = document.querySelector(".likebox1");


function like1(){
    likecount++;
    likespan1.innerText = likecount + "like(s)";

}

var likecount=12;
var likespan2 = document.querySelector(".likebox2");


function like2(){
    likecount++;
    likespan2.innerText = likecount + "like(s)";
}

var likecount=9;
var likespan3 = document.querySelector(".likebox3");


function like3(){
    likecount++;
    likespan3.innerText = likecount + "like(s)";
}



